name: Tauri v2 Release Process
on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  UBUNTU: "ubuntu-20.04"
  MACOS: "macos-latest"
  WINDOWS: "windows-latest"
  CN_APPLICATION: "MeadTools/MeadTools"

steps:
  - uses: actions/checkout@v4
  - name: create draft release
    uses: crabnebula-dev/cloud-release@v0
    with:
      command: release draft ${{ env.CN_APPLICATION }} --framework tauri
      api-key: ${{ secrets.CN_API_KEY }}

build:
  needs: draft

  strategy:
    fail-fast: false
    matrix:
      os:
        - ${{ env.UBUNTU }}
        - ${{ env.MACOS }}
        - ${{ env.WINDOWS }}

  runs-on: ${{ matrix.os }}

  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: "20"
    - name: Install stable toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
        cache: true

    - name: install Linux dependencies
      if: matrix.os == '${{ env.UBUNTU }}'
      run: |
        sudo apt-get update
        sudo apt-get install -y webkit2gtk-4.1

    - name: build Tauri app for Windows, Linux
      if: matrix.os != '${{ env.MACOS }}'
      run: |
        npm ci
        npm run tauri build
      env:
        TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
        TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}

    - name: Install x86_64-apple-darwin for mac and build Tauri binaries
      if: matrix.os == 'macos-latest'
      run: |
        rustup target add x86_64-apple-darwin
        npm ci
        npm run tauri build -- --target x86_64-apple-darwin
        npm run tauri build -- --target aarch64-apple-darwin
      env:
        TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
        TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}

    - name: upload assets
      uses: crabnebula-dev/cloud-release@v0
      with:
        command: release upload ${{ env.CN_APPLICATION }} --framework tauri
        api-key: ${{ secrets.CN_API_KEY }}
        path: ./src-tauri

publish:
  needs: build

  runs-on: ${{ env.UBUNTU }}

  steps:
    - uses: actions/checkout@v4

    - name: publish release
      uses: crabnebula-dev/cloud-release@v0
      with:
        command: release publish ${{ env.CN_APPLICATION }} --framework tauri
        api-key: ${{ secrets.CN_API_KEY }}
